from mintflow.application.authentication.audit import (
    AUTHENTICATION_AUDIT_RETENTION,
    AuthenticationAuditAppender,
    AuthenticationAuditEventType,
    AuthenticationAuditOutcome,
    AuthenticationAuditRecord,
    authentication_audit_cutoff,
    is_authentication_audit_record_eligible,
)
from mintflow.application.authentication.email import NormalizedEmail, normalize_email
from mintflow.application.authentication.login_challenge import (
    GENERIC_MAGIC_LINK_REQUEST_RESULT,
    INVALID_MAGIC_LINK_CONSUMPTION_RESULT,
    AuthenticatedUserIdentity,
    ConsumeMagicLink,
    EmailDeliveryError,
    LoginChallenge,
    MagicLinkConsumptionResult,
    MagicLinkMessage,
    MagicLinkRequestResult,
    RequestMagicLink,
)
from mintflow.application.authentication.magic_link import MagicLinkBuilder
from mintflow.application.authentication.tokens import GeneratedToken, generate_token, hash_token
from mintflow.application.authentication.web_session import (
    WEB_SESSION_LIFETIME,
    AuthenticatedWebSession,
    AuthenticateWebSession,
    RevokeAllWebSessions,
    RevokeWebSession,
    WebSession,
    new_web_session,
)

__all__ = [
    "AUTHENTICATION_AUDIT_RETENTION",
    "AuthenticationAuditAppender",
    "AuthenticationAuditEventType",
    "AuthenticationAuditOutcome",
    "AuthenticationAuditRecord",
    "GENERIC_MAGIC_LINK_REQUEST_RESULT",
    "INVALID_MAGIC_LINK_CONSUMPTION_RESULT",
    "AuthenticatedUserIdentity",
    "AuthenticatedWebSession",
    "AuthenticateWebSession",
    "ConsumeMagicLink",
    "EmailDeliveryError",
    "GeneratedToken",
    "LoginChallenge",
    "MagicLinkConsumptionResult",
    "MagicLinkBuilder",
    "MagicLinkMessage",
    "MagicLinkRequestResult",
    "NormalizedEmail",
    "RequestMagicLink",
    "RevokeAllWebSessions",
    "RevokeWebSession",
    "WEB_SESSION_LIFETIME",
    "WebSession",
    "authentication_audit_cutoff",
    "generate_token",
    "hash_token",
    "is_authentication_audit_record_eligible",
    "normalize_email",
    "new_web_session",
]
